import streamlit as st
from ai71 import AI71
from dotenv import load_dotenv
import os


class Diagnose:
    def __init__(self):
        # loading environment variables from .env file
        load_dotenv()
        self.AI71_API_KEY = os.getenv("AI71_API_KEY")
        self.client = AI71(self.AI71_API_KEY)

    def app(self):

        # Custom CSS for styling FAQs
        custom_css = """
        <style>
        .initial-message {
            color: black;
            padding: 5px;  /* Padding around the content */
            font-size: 17px;  /* Larger font size */
            line-height: 1.5;  /* Slightly increased line height for readability */
            text-align: center;
            margin-bottom: 10px;
            margin-top: 10px;
        }
        </style>
        """
        st.markdown(custom_css, unsafe_allow_html=True)

        # Streamlit UI components
        st.markdown("""
        <div style="background-color: #000066; text-align: center; padding: 10px;border-radius:5px;margin-bottom:20px;">
          <h1 style="color: white; font-size: 70px; margin-bottom: -40px;">Medicano</h1>
          <h2 style="color: white; font-size: 20px; margin-top: 5px;">A Medical Assistant</h2>
        </div>
        """, unsafe_allow_html=True)

        with st.form("diagnose_form"):
            options = [
                "Cholangitis",
                "Cholecystitis",
                "Cholelithiasis",
                           "Abdominal pain",
            "Abnormal bleeding",
            "Acne",
            "Aching muscles",
            "Aching joints",
            "Aggression",
            "Agitation",
            "Allergic reaction",
            "Alopecia",
            "Altered taste",
            "Amnesia",
            "Anemia",
            "Angina",
            "Anxiety",
            "Apathy",
            "Aphasia",
            "Apnea",
            "Appetite loss",
            "Arrhythmia",
            "Arthritis",
            "Asthma",
            "Ataxia",
            "Atrial fibrillation",
            "Back pain",
            "Bloating",
            "Blurry vision",
            "Bone pain",
            "Breast pain",
            "Bronchitis",
            "Bruising",
            "Burning sensation",
            "Cachexia",
            "Chest pain",
            "Chills",
            "Clammy skin",
            "Confusion",
            "Conjunctivitis",
            "Constipation",
            "Cough",
            "Cramps",
            "Cyanosis",
            "Dehydration",
            "Delirium",
            "Delusions",
            "Depression",
            "Diabetes",
            "Diarrhea",
            "Dizziness",
            "Dry eyes",
            "Dry mouth",
            "Dysphagia",
            "Dysuria",
            "Earache",
            "Edema",
            "Emesis",
            "Epistaxis",
            "Erythema",
            "Excessive sweating",
            "Exhaustion",
            "Eye pain",
            "Fainting",
            "Fatigue",
            "Fever",
            "Flank pain",
            "Flatulence",
            "Flushing",
            "Frequent urination",
            "Gait disturbance",
            "Hallucinations",
            "Headache",
            "Heart palpitations",
            "Hematemesis",
            "Hematuria",
            "Hemoptysis",
            "Hiccups",
            "High blood pressure",
            "Hoarseness",
            "Hot flashes",
            "Hyperactivity",
            "Hyperhidrosis",
            "Hyperventilation",
            "Hypersensitivity",
            "Hypotension",
            "Incontinence",
            "Indigestion",
            "Infertility",
            "Insomnia",
            "Irregular heartbeat",
            "Irritability",
            "Itching",
            "Jaundice",
            "Joint stiffness",
            "Lethargy",
            "Lightheadedness",
            "Loss of appetite",
            "Low blood pressure",
            "Low libido",
            "Lower back pain",
            "Lump or mass",
            "Memory loss",
            "Menstrual irregularities",
            "Mood swings",
            "Mouth ulcers",
            "Muscle cramps",
            "Muscle weakness",
            "Nasal congestion",
            "Nausea",
            "Neck pain",
            "Night sweats",
            "Numbness",
            "Obesity",
            "Painful urination",
            "Palpitations",
            "Paralysis",
            "Paresthesia",
            "Peripheral edema",
            "Photophobia",
            "Pneumonia",
            "Polyuria",
            "Postnasal drip",
            "Pruritus",
            "Rashes",
            "Rectal bleeding",
            "Restlessness",
            "Rhinorrhea",
            "Seizures",
            "Shortness of breath",
            "Sinusitis",
            "Skin discoloration",
            "Sleep apnea",
            "Sleep disturbances",
            "Sneezing",
            "Sore throat",
            "Spasms",
            "Speech difficulties",
            "Stiff neck",
            "Stomach pain",
            "Stress",
            "Swallowing difficulties",
            "Sweating",
            "Swelling",
            "Syncope",
            "Tachycardia",
            "Tearing",
            "Tinnitus",
            "Tremors",
            "Urticaria",
            "Vertigo",
            "Vision changes",
            "Vomiting",
            "Wheezing",
            "Weight gain",
            "Weight loss",
            "Wrist pain",
            "Yellowing of the skin",
            "Zoster",
            "Abscess",
            "Acromegaly",
            "Addison's disease",
            "AIDS",
            "Alcoholism",
            "Aneurysm",
            "Anorexia",
            "Anxiety disorder",
            "Appendicitis",
            "Arteriosclerosis",
            "Asperger syndrome",
            "Atherosclerosis",
            "Attention deficit disorder",
            "Autism",
            "Bacterial infection",
            "Bipolar disorder",
            "Bladder infection",
            "Bleeding gums",
            "Blood clot",
            "Bone fracture",
            "Brain injury",
            "Breast lump",
            "Bronchiectasis",
            "Bronchospasm",
            "Bursitis",
            "Celiac disease",
            "Cerebral palsy",
            "Chronic fatigue syndrome",
            "Cirrhosis",
            "Claudication",
            "Cluster headache",
            "Cognitive decline",
            "Colitis",
            "Concussion",
            "Congestive heart failure",
            "Coronary artery disease",
            "Crohn's disease",
            "Cushing's syndrome",
            "Cystitis",
            "Dandruff",
            "Deafness",
            "Deep vein thrombosis",
            "Dementia",
            "Dengue fever",
            "Dermatitis",
            "Diabetic neuropathy",
            "Diabetic retinopathy",
            "Digestive disorders",
            "Down syndrome",
            "Dyslexia",
            "Dystonia",
            "Eczema",
            "Emphysema",
            "Encephalitis",
            "Endocarditis",
            "Endometriosis",
            "Epilepsy",
            "Erectile dysfunction",
            "Esophagitis",
            "Fibromyalgia",
            "Gallstones",
            "Gastritis",
            "Gastroenteritis",
            "Gastroesophageal reflux disease",
            "Genital herpes",
            "Glaucoma",
            "Goiter",
            "Gout",
            "Graves' disease",
            "Guillain-Barre syndrome",
            "Gynecomastia",
            "Hemorrhoids",
            "Hepatitis",
            "Herniated disc",
            "Herpes zoster",
            "Hidradenitis suppurativa",
            "HIV",
            "Hodgkin's lymphoma",
            "Huntington's disease",
            "Hypercalcemia",
            "Hyperlipidemia",
            "Hyperparathyroidism",
            "Hypertension",
            "Hyperthyroidism",
            "Hypoglycemia",
            "Hypoparathyroidism",
            "Hypothyroidism",
            "Immunodeficiency",
            "Impetigo",
            "Infectious mononucleosis",
            "Influenza",
            "Interstitial cystitis",
            "Irritable bowel syndrome",
            "Kidney infection",
            "Kidney stones",
            "Lactose intolerance",
            "Laryngitis",
            "Leukemia",
            "Liver disease",
            "Lupus",
            "Lymphedema",
            "Lymphoma",
            "Malaria",
            "Mania",
            "Melanoma",
            "Meniere's disease",
            "Meningitis",
            "Menopause",
            "Migraine",
            "Miscarriage",
            "Multiple sclerosis",
            "Muscular dystrophy",
            "Myasthenia gravis",
            "Myocardial infarction",
            "Narcolepsy",
            "Nephritis",
            "Neuralgia",
            "Neurofibromatosis",
            "Neuropathy",
            "Non-Hodgkin's lymphoma",
            "Obesity",
            "Obsessive-compulsive disorder",
            "Osteoarthritis",
            "Osteomyelitis",
            "Osteoporosis",
            "Otitis media",
            "Ovarian cysts",
            "Pancreatitis",
            "Parkinson's disease",
            "Peptic ulcer disease",
            "Pericarditis",
            "Peripheral artery disease",
            "Peripheral neuropathy",
            "Pharyngitis",
            "Pleurisy",
            "Pneumothorax",
            "Polycystic ovary syndrome",
            "Post-traumatic stress disorder",
            "Psoriasis",
            "Pulmonary embolism",
            "Pulmonary fibrosis",
            "Raynaud's disease",
            "Renal failure",
            "Respiratory distress",
            "Restless legs syndrome",
            "Rheumatic fever",
            "Rheumatoid arthritis",
            "Rosacea",
            "Sarcoidosis",
            "Schizophrenia",
            "Sciatica",
            "Scleroderma",
            "Septicemia",
            "Shingles",
            "Sinus infection",
            "Sleep disorder",
            "Spinal stenosis",
            "Stroke",
            "Substance abuse",
            "Systemic lupus erythematosus",
            "Thrombocytopenia",
            "Thyroid disease",
            "Tonsillitis",
            "Tourette syndrome",
            "Tuberculosis",
            "Ulcerative colitis",
            "Urinary tract infection",
            "Uterine fibroids",
            "Varicose veins",
            "Viral infection",
            "Vitamin deficiency",
            "Vitiligo",
            "Vomiting blood",
            "Warts",
            "Wilms tumor",
            "Wilson's disease",
            "Yellow fever",
            "Zika virus",
            "Abdominal distension",
            "Acid reflux",
            "Agoraphobia",
            "Alcohol withdrawal",
            "Allodynia",
            "Amniotic fluid embolism",
            "Anaphylaxis",
            "Aneurysm rupture",
            "Angioedema",
            "Ankylosing spondylitis",
            "Anorexia nervosa",
            "Anthrax",
            "Aortic dissection",
            "Aplastic anemia",
            "Arterial embolism",
            "Arthralgia",
            "Asbestosis",
            "Aspergillosis",
            "Asthenia",
            "Atrial flutter",
            "Bacterial vaginosis",
            "Barrett's esophagus",
            "Basal cell carcinoma",
            "Bell's palsy",
            "Benign prostatic hyperplasia",
            "Biliary colic",
            "Blastomycosis",
            "Botulism",
            "Bradycardia",
            "Brain aneurysm",
            "Brain tumor",
            "Breast abscess",
            "Breast engorgement",
            "Bronchial asthma",
            "Bulimia nervosa",
            "Bursitis",
            "Cachectic",
            "Calf pain",
            "Cancer",
            "Canker sores",
            "Cardiomyopathy",
            "Catatonia",
            "Cellulitis",
            "Chancroid",
            "Chikungunya",
            "Chlamydia"
            ]
            symptoms = st.multiselect("Select Your Symptoms", options)
            submit_diagnose = st.form_submit_button("Diagnose")

            if submit_diagnose:
                prompt = (
                    f"Based on the symptoms listed: {symptoms}, please perform a detailed diagnostic analysis. "
                    f"Your task is to provide a comprehensive overview of the potential disease, including the following sections:\n"
                    f"- **Disease Name**: Clearly state the name of the disease.\n"
                    f"- **History**: Describe the historical context and background of the disease.\n"
                    f"- **Introduction**: Provide an introduction to the disease, including its significance and impact.\n"
                    f"- **Causes**: Outline the primary causes and contributing factors of the disease.\n"
                    f"- **Symptoms**: List and explain the symptoms associated with the disease.\n"
                    f"- **Side Effects**: Detail any potential side effects related to the disease or its treatments.\n"
                    f"- **Measures to Cure**: Recommend treatment options and measures to cure or manage the disease.\n"
                    f"Please ensure that each section is well-organized with clear headings. Additionally, include relevant hyperlinks where applicable:\n"
                    f"- **Blog Links**: For additional readings and blog posts.\n"
                    f"- **Article Links**: For scholarly articles and research papers.\n"
                    f"Ensure the output is professionally structured and provides valuable information for users seeking medical advice."
                )

                response = self.client.chat.completions.create(
                    model="tiiuae/falcon-180b-chat",
                    messages=[
                        {"role": "system", "content": "You are a medical assistant."},
                        {"role": "user", "content": prompt},
                    ],
                    stream=True,
                )

                # Collect the streamed response content
                response_content = ""
                for chunk in response:
                    if chunk.choices[0].delta.content:
                        response_content += chunk.choices[0].delta.content

                st.title("Disease Diagnosis")
                st.markdown(response_content)
